export const GET_PRODUCT= 'GET_PRODUCT';
export const DELETE_PRODUCT= 'DELETE_PRODUCT';
export const EDIT_PRODUCT= 'EDIT_PRODUCT';
export const ADD_PRODUCT= 'ADD_PRODUCT';
export const SEARCH_BY_NAME= 'SEARCH_BY_NAME'